#!/bin/sh

start() {
	printf "Starting zicBox: "
    setterm --cursor off --blank force --clear > /dev/tty1
	cd /opt/zicBox && ./pixel >> /var/log/pixel.log 2>&1 &
	echo "OK"
}
stop() {
	printf "Stopping zicBox: "
	killall pixel
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?