#!/bin/sh

case "$1" in
    start)
        echo "Starting Wi-Fi connection..."
        wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf -B
        udhcpc -i wlan0
        ;;
    stop)
        echo "Stopping Wi-Fi connection..."
        killall wpa_supplicant
        killall udhcpc
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
